### ISSUE TITLE
odd newline & indentation choices

### ISSUE THREAD

**Issue by tjhance** [verus-lang/verusfmt#68]
From vstd/storage_protocol.rs:

```
    forall|q: P|
        #![all_triggers]
        P::op(p1, q).inv() ==> P::op(p2, q).inv() && P::op(p1, q).interp().dom().disjoint(b1.dom())
            && P::op(p2, q).interp().dom().disjoint(b2.dom()) && P::op(
            p1, 
            q,  
        ).interp().union_prefer_right(b1) =~= P::op(p2, q).interp().union_prefer_right(b2)
```

very strange indentation choices here

**Comment by parno** [comment]
We have an exception for `#[trigger]`, but otherwise, attributes always go on their own line; we could consider adding `#![all_triggers]` to that exception list.  The indentation of the `&& P` is expected, since we filled up the previous line, and the formatter is allowed to break lines before binary operators like `&&`, which it then indents.  The architecture of `verusfmt` doesn't allow prioritizing line breaks, so we can't say that we might prefer it to break after, say, the implication.  The line breaks before the arguments to `op` are also expected, once you need to break up a function call.  The one oddity is that we might hope for those arguments to be indented one more time relative to the previous line.  There's probably some unfortunate interaction between the various levels of nested indents, but I think this falls into the category of "pull request welcome".
